### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yaxit24**
Here I have added more details in each step for the students participating for the first time for the Hacktoberfest . so by reading it anyone would be able to make a clear idea and important points required.

## Description

Please include a summary of the changes and the related issue(s) this pull request addresses. Include any relevant context or background information.

Fixes: #[issue_number] (replace with the issue number, if applicable)

Use [x] to represent a checked (ticked) box.✅
Use [ ] to represent an unchecked box.❌

## Type of Change

- [ ] Question Added
- [ ] Solution Added
- [ ] Other (please specify):

## How to Test

Provide a brief description of how to test your changes. Include steps, commands, or screenshots if necessary.

1. Step 1
2. Step 2
3. Step 3

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have added tests to cover my changes (if applicable).
- [ ] All new and existing tests pass.

## Additional Notes

Please add any other information that is relevant to this pull request, including potential risks, alternative solutions considered, or future improvements.

### CODE REVIEW

**Comment by Gyanthakur** [comment]
you are not following my account.

**Comment by yaxit24** [comment]
yes, also request sent on linkdeln, please accept it.

**Comment by yaxit24** [comment]
I have followed, thank you for accepting my request at Linkeln, I'm sorry
for the inconvenience due to delay for the same.

**Review by Gyanthakur — APPROVED** [review]

**Comment by yaxit24** [comment]
Thank you so much for accepting my proposed changes! I’m thrilled to know that my contributions could add value to the project. Your feedback and collaboration make all the difference, and I’m excited to continue working together to make this even better. Thanks again for your support — looking forward to the next steps!

**Pull request merged**
